version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    ports:
      - 7000:7000
    command: npm run start
    depends_on:
      - postgres
  postgres:
      container_name: postgres
      image: postgres
      env_file:
        - .production.env
      environment:
        PG_DATA: /var/lib/postgresql/data
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: always

volumes:
  pgdata: